function [R_skew] = skewVec(x)
% Skew symmetric matrix - cross product as matrix multiplication vector
% wise nx3 -> nx3x3
% R_skew(X)Y = X x Y
n = size(x,1);
R_skew = cat(3, ...
    [ zeros(n,1),   -x(:,3),     x(:,2) ], ...
    [    x(:,3), zeros(n,1),    -x(:,1) ], ...
    [   -x(:,2),     x(:,1), zeros(n,1) ] ...
);
end

